print("Injecting Necronomicon taunts.")

if (PROP_TAUNTS == nil) then
    PROP_TAUNTS = {}
end

PROP_TAUNTS["Right Round"]                  = "taunts/rightround.wav"
PROP_TAUNTS["Tokyo"]                        = "taunts/tokyo.wav"
PROP_TAUNTS["Meeseeks"]                     = "taunts/meeseeks.wav"
PROP_TAUNTS["Roped Into This"]              = "taunts/roped_me_into_this.wav"
PROP_TAUNTS["Tube Man"]                     = "taunts/tubeman.wav"
PROP_TAUNTS["Mario Dreaming"]               = "taunts/sm64_mario_dreaming.wav"
PROP_TAUNTS["Bane Blow Up"]                 = "taunts/bane_blow_up.wav"
PROP_TAUNTS["Bold Strategy"]                = "taunts/bold_strategy.wav"
PROP_TAUNTS["Danger Zone"]                  = "taunts/danger_zone.wav"
--PROP_TAUNTS["Dial Up (Long)"]               = "taunts/dial_up_long.wav"
PROP_TAUNTS["Food Fight"]                   = "taunts/food_fight.wav"
PROP_TAUNTS["Good Eye"]                     = "taunts/good_eye.wav"
PROP_TAUNTS["Heyayayayay"]                  = "taunts/heyayayayay.wav"
PROP_TAUNTS["Homer Pistol Whip"]            = "taunts/homer_pistol_whip.wav"
PROP_TAUNTS["Ignore Me"]                    = "taunts/ignore_me.wav"
PROP_TAUNTS["I Make This Look Good"]        = "taunts/i_make_this_look_good.wav"
PROP_TAUNTS["You Didnt See Anything"]       = "taunts/madagascar-you-didnt-see-anything.wav"
PROP_TAUNTS["Magic Cloak"]                  = "taunts/magic_cloak.wav"
PROP_TAUNTS["Main Characters"]              = "taunts/main_characters.wav"
PROP_TAUNTS["Narf"]                         = "taunts/narf.wav"
PROP_TAUNTS["NOFU Vowel"]                   = "taunts/near_open_front_unrounded_vowel.wav"
PROP_TAUNTS["Oh Hi Mark"]                   = "taunts/oh_hi_mark.wav"
PROP_TAUNTS["Only Fools are Positive"]      = "taunts/only_fools_are_positive.wav"
PROP_TAUNTS["Pinky and the Brain"]          = "taunts/pinky_and_the_brain.wav"
PROP_TAUNTS["Potato Chip"]                  = "taunts/potato_chip_and_eat_it.wav"
PROP_TAUNTS["Power Glove"]                  = "taunts/power_glove.wav"
PROP_TAUNTS["Princess Bride"]               = "taunts/princess_bride.wav"
PROP_TAUNTS["Regular Dude"]                 = "taunts/regular_dude.wav"
PROP_TAUNTS["Right Round (Long)"]           = "taunts/rightround_long.wav"
PROP_TAUNTS["Skifree Yeti Argh"]            = "taunts/skifree_yeti_argh.wav"
PROP_TAUNTS["Smoke Weed Everyday"]          = "taunts/smoke_weed_everyday.wav"
PROP_TAUNTS["Smoke Weed Everyday (Long)"]   = "taunts/smoke_weed_everyday_long.wav"
PROP_TAUNTS["Surprise Motherfucker"]        = "taunts/surprise_motherfucker.wav"
PROP_TAUNTS["Taco Bell"]                    = "taunts/taco_bell.wav"
PROP_TAUNTS["Thats Pathetic"]               = "taunts/thats_pathetic.wav"
PROP_TAUNTS["The Flesh Is A Gift"]          = "taunts/the_flesh_is_a_gift.wav"
PROP_TAUNTS["The Flesh Is A Gift (Long)"]   = "taunts/the_flesh_is_a_gift_long.wav"
PROP_TAUNTS["Toaster"]                      = "taunts/toaster.wav"
PROP_TAUNTS["Turn Down for Whhat"]          = "taunts/turn_down_for_whhat.wav"
PROP_TAUNTS["We Aint Found Shit"]           = "taunts/we_aint_found_shit.wav"
PROP_TAUNTS["What a Savings"]               = "taunts/what_a_savings.wav"
PROP_TAUNTS["Young Frankenstein Espresso"]  = "taunts/young_frank_espresso.wav"
PROP_TAUNTS["Your Mother was a Hamster"]    = "taunts/your_mother_was_a_hamster.wav"
PROP_TAUNTS["You Lose"]                     = "taunts/you_lose.wav"
PROP_TAUNTS["Im a Blender"]                 = "taunts/rango-im-a-blender.wav"
PROP_TAUNTS["I have the High Ground"]       = "taunts/high_ground.wav"
PROP_TAUNTS["Pink Panther"]                 = "taunts/pink_panther.wav"
PROP_TAUNTS["Keep Absolutely Still"]        = "taunts/jurassic_park_keep_absolutely_still.wav"
PROP_TAUNTS["War Room"]                     = "taunts/war_room.wav"
PROP_TAUNTS["Dont Blink"]                   = "taunts/dont_blink_short.wav"
PROP_TAUNTS["Dont Blink (Long)"]            = "taunts/dont_blink.wav"
PROP_TAUNTS["Nonchalant"]                   = "taunts/nonchalant.wav"
PROP_TAUNTS["Zelda Find"]                   = "taunts/zelda_find.wav"
PROP_TAUNTS["Boilin Toilet"]                = "taunts/boilin_toilet.wav"
PROP_TAUNTS["Dude as Dude"]                 = "taunts/dude_as_dude.wav"
PROP_TAUNTS["Dont be Suspicious"]           = "taunts/dont_be_suspicious.wav"
PROP_TAUNTS["TF2 Red Spy"]                  = "taunts/red_spy.wav"
PROP_TAUNTS["ShapirHo"]                     = "taunts/shapirho.wav"
PROP_TAUNTS["Scatman's World"]              = "taunts/scatmans_world.wav"
PROP_TAUNTS["All I want for Xmas"]          = "taunts/all_i_want_for_christmas.wav"
PROP_TAUNTS["Chug Jug with You"]            = "taunts/chug_jug_with_you.wav"
PROP_TAUNTS["Escape Capitalism"]            = "taunts/escape_capitalism.wav"
PROP_TAUNTS["Bender Over There"]            = "taunts/over_there.wav"
--PROP_TAUNTS["HaHaHa Seattle (Long)"]      = "taunts/seattle_long.wav"
PROP_TAUNTS["HaHaHa Seattle"]               = "taunts/seattle.wav"
PROP_TAUNTS["Krieger's Bathrooms"]          = "taunts/bathroom_1.wav"
PROP_TAUNTS["Little Pogchamp"]              = "taunts/little_pogchamp.wav"
PROP_TAUNTS["Carl - Go Away"]               = "taunts/carl_go_away.wav"
PROP_TAUNTS["Carl - Deal With You Animals"] = "taunts/carl_deal_with_you_animals.wav"
PROP_TAUNTS["Carl - Physical Fitness"]      = "taunts/carl_physical_fitness.wav"
PROP_TAUNTS["Cruisin for a Brusin"]         = "taunts/cruisin_for_a_brusin.wav"
PROP_TAUNTS["Killinger - Silly Billy"]      = "taunts/killinger_silly_billy.wav"
PROP_TAUNTS["No Idea What I'm Doing"]       = "taunts/no_idea.wav"
PROP_TAUNTS["Stolkholm Syndrome; Handsome"] = "taunts/stolkholm_syndrome.wav"
PROP_TAUNTS["What is That! What is That!"]  = "taunts/what_is_that.wav"
PROP_TAUNTS["Dr. Zaius"]                    = "taunts/dr_zaius.wav"
PROP_TAUNTS["Semper Fidelis Tyrannosaurus"] = "taunts/semper_fidelis_tyrannosaurus.wav"
PROP_TAUNTS["Johnny Bravo - I'm Real"]      = "taunts/jb_im_real.wav"
PROP_TAUNTS["Carmelldownsen"]               = "taunts/carmelldownsen.wav"
PROP_TAUNTS["I'm Me, He Says"]              = "taunts/im_me_he_says.wav"
PROP_TAUNTS["Darkness"]                     = "taunts/darkness.wav"
PROP_TAUNTS["Mickey It's Riku... What"]     = "taunts/mickey_its_riku_what.wav"
PROP_TAUNTS["Simple and Clean"]             = "taunts/simple_and_clean.wav"
PROP_TAUNTS["I was the Turkey"]             = "taunts/i_was_the_turkey.wav"
PROP_TAUNTS["F in the Chat for Goofy"]      = "taunts/f_in_the_chat_for_goofy.wav"
PROP_TAUNTS["My Friends are My Power"]      = "taunts/my_friends_are_my_power.wav"
PROP_TAUNTS["Inspector Gadget"]             = "taunts/inspector_gadget.wav"
PROP_TAUNTS["I am the Box Ghost"]           = "taunts/i_am_the_box_ghost.wav"
PROP_TAUNTS["Everybody Get Up Time to Slam"]= "taunts/everybody_get_up_its_time_to_slam_now.wav"
PROP_TAUNTS["Come on and Slam"]             = "taunts/come_on_and_slam.wav"
PROP_TAUNTS["Move Bitch"]                   = "taunts/move_bitch.wav"
PROP_TAUNTS["Who Lives Who Dies"]           = "taunts/who_lives_who_dies.wav"
PROP_TAUNTS["MMM Whatcha Say"]              = "taunts/mmm_whatcha_say.wav"
PROP_TAUNTS["Fools Who Run Their Mouths"]   = "taunts/fools_who_run_their_mouths_off.wav"
PROP_TAUNTS["Lead them on a Merry Chase"]   = "taunts/merry_chase.wav"

-- A gift for Kevin...
local plymeta = FindMetaTable("Player")
if (plymeta.SetPlayerColorWrapped == nil) then
    plymeta.SetPlayerColorWrapped = plymeta.SetPlayerColor
end
function plymeta:SetPlayerColor(color)
    local steamID3 = self:AccountID()
    if (steamID3 == 28456070 and math.random(10) == 10) then
        -- Pantone 448 C
        color = Vector(0.2890625, 0.25390625, 0.1640625)
    elseif (steamID3 == 36442492) then
        color = Vector(math.Rand(0, 1), math.Rand(0, 1), math.Rand(0, 1))
    end
    self:SetPlayerColorWrapped(color)
end
